version: '3'

services:
  devices-db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=${DEVICES_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DEVICES_MYSQL_DATABASE}
      - MYSQL_USER=${DEVICES_MYSQL_USER}
      - MYSQL_PASSWORD=${DEVICES_MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - devices-data:/var/lib/mysql

volumes:
  devices-data: